title: mm-ADT
description: A Multi-Model Abstract Data Type
url: mm-adt.org
author: _mmadt
twitter:
  username: _mmadt
theme: jekyll-theme-tactile
google_analytics: UA-136594745-2
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class   : 'syntax'
